.Dd July 17, 2026
.Dt _DEBUG 1
.Os
.Sh NAME
.Nm _debug
.Nd userspace volatile testing and debugging utility
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
The
.Nm
utility is a playground for testing various things in userspace.
.Pp
This is a volatile testing tool, so its code, behavior, and output will change often.
.Sh EXIT STATUS
.Ex -std
